add option -C

diff --git a/github_keygen b/github_keygen
--- a/github_keygen
+++ b/github_keygen
@@ -1,9 +1,29 @@
 #! /bin/sh
+COMMENT="default"
+
+# option
+while getopts C: OPT
+do
+  case $OPT in
+    C)  COMMENT=$OPTARG
+        ;;
+    \?) echo "\nUsage: github_keygen [-C comment] project\n" 1>&2
+        exit 1
+        ;;
+  esac
+done
+shift `expr $OPTIND - 1`
+
+# Exit if project is null
+if [ -z $1 ]; then
+  echo "\nUsage: github_keygen [-C comment] project\n" 1>&2
+  exit 1
+fi
 
 # Exit if the same name key exists
 if [ -f $HOME/.ssh/$1.pub ]; then
-  echo "[ERROR] The key for the project '$1' has already exists."
-  exit
+  echo "\n[ERROR] The key for the project '$1' has already exists.\n"
+  exit 1
 fi
 
 # generate rsa key
